package remote_broker

const (
	REMOTE_BROKER_API_HOST = "REMOTE_BROKER_API_HOST"
	REMOTE_BROKER_API_PORT = "REMOTE_BROKER_API_PORT"
	REMOTE_BROKER_WS_HOST  = "REMOTE_BROKER_WS_HOST"
	REMOTE_BROKER_WS_PORT  = "REMOTE_BROKER_WS_PORT"
)
