package rsend_broker

const (
	RSEND_BROKER_API_HOST = "RSEND_BROKER_API_HOST"
	RSEND_BROKER_API_PORT = "RSEND_BROKER_API_PORT"
	RSEND_BROKER_WS_HOST  = "RSEND_BROKER_WS_HOST"
	RSEND_BROKER_WS_PORT  = "RSEND_BROKER_WS_PORT"
)
