name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deps:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get dependencies
      run: task build