name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Task
      uses: Arduino/actions/setup-taskfile@master
    - name: Get dependencies
      run: task build